--oauth2-client-id=77185425430.apps.googleusercontent.com
--oauth2-client-secret=OTJgUOQcT7lO7GsGZq2G4IlT
--ozone-platform=wayland
--enable-features=WaylandWindowDecorations,WaylandPerSurfaceScale,WaylandUiScale,WaylandFractionalScaleV1
--enable-wayland-ime
