exec-once = sleep 5 && hyprctl reloadconfig
exec-once = sleep 4 && qs -c noctalia-shell
exec-once = uwsm-app -- Telegram -startintray
exec-once = uwsm-app -- steam -silent

exec-once = sleep 6 && uwsm-app -- vesktop -m
