# left screen tag and rules
workspace = 1, monitor:DP-2, persistent:true
windowrule = tag +leftscreen, match:class ^(org\.telegram\.desktop)$
windowrule = tag +leftscreen, match:class ^(YandexMusic)$
windowrule = tag +leftscreen, match:class ^(vesktop)$
windowrule = workspace 1 silent, match:tag leftscreen

# choosefile float
windowrule = tag +choosefile, match:title ^(Choose Files)$
windowrule = float true, match:tag choosefile
windowrule = center on, match:tag choosefile

