monitor=,preferred,auto,auto
monitor=DP-2,2560x1440@143.97,0x0,1.25,transform,3,bitdepth,10,cm,wide
monitor=DP-3,3840x2160@239.99,1152x608,1.5,bitdepth,10,cm,wide
monitor=HDMI-A-1,disable

render {
  cm_auto_hdr = 0
}
