# hyprshot -m region                                  # выделить область, сохранить + копировать
# hyprshot -m output                                  # весь экран сохранить
# hyprshot -m window --freeze                         # активное окно с заморозкой
# hyprshot -m region --clipboard-only                 # только в буфер
# hyprshot -m region -o ~/Documents/specifs           # в нестандартную папку
# Биндинги в Hyprland
# В ~/.config/hypr/hyprland.conf добавь:
# # Скриншоты
bind = $mainMod SHIFT, S, exec, hyprshot -m region --clipboard-only                           # PrintScreen — выделение области
# bind = $mainMod CTRL SHIFT, S, exec, hyprshot -m region --raw | satty --copy-command wl-copy --early-exit -f -                           # PrintScreen — выделение области
bind = $mainMod CTRL SHIFT, S, exec, hyprshot -m region --raw | satty -f -                           # PrintScreen — выделение области
# bind = SHIFT, Print, exec, hyprshot -m window                       # Shift+PrintScreen — активное окно
bind = CTRL, Print, exec, hyprshot -m output                        # Ctrl+PrintScreen — весь монитор
# bind = SUPER, Print, exec, hyprshot -m region --clipboard-only      # Super+PrintScreen — только в буфер
