hl.on("hyprland.start", function()
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("uwsm-app -- Telegram -startintray")
	hl.exec_cmd("uwsm-app -- steam -silent")
	hl.exec_cmd("sleep 2 && uwsp-app -- vesktop -m")
end)
